### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [SomeoneElseOSM/openstreetmap-carto-AJT#1]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project seems to be using curl, which [will not follow redirects by default](https://davidwalsh.name/curl-follow-redirects).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https?

**Comment by SomeoneElseOSM** [comment]
Thanks - I had no idea that http://planet.openstreetmap.org/historical-shapefiles/world_boundaries-spherical.tgz even still existed, never mind that I actually used it.  That script actually tends to need adjustment every time it is run due to naturalearthdata moving stuff around.

**Comment by SomeoneElseOSM** [comment]
Resolved by https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/commit/dceb7de0d9a9dc8787a2964700de5975f5c8a0eb (and for info Natural Earth stuff hasn't moved in a couple of months).
