### ISSUE TITLE
DeprecationWarning: Invalid 'main' field in + Styles do not match layer selector

### ISSUE THREAD

**Issue by simwin** [SomeoneElseOSM/openstreetmap-carto-AJT#4]
```
git clone git://github.com/SomeoneElseOSM/openstreetmap-carto-AJT.git
cd openstreetmap-carto-AJT
carto -v
1.2.0
carto project.mml > mapnik.xml

```
```
Warning: style/admin.mss:24:19 Styles do not match layer selector #admin-low-zoom.
Warning: style/admin.mss:23:19 Styles do not match layer selector #admin-low-zoom.
Warning: style/admin.mss:22:18 Styles do not match layer selector #admin-low-zoom.
Warning: style/admin.mss:18:6 Styles do not match layer selector #admin-low-zoom.

```
```
node:75557) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/share/node_modules/chroma-js/package.json' of 'chroma.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:75557) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/share/node_modules/chroma-js/package.json' of 'chroma.js'. Please either fix that or report it to the module author
```

**Comment by SomeoneElseOSM** [comment]
Thanks for raising this.  I've tended to ignore those messages as they're only warnings and everything still works.  I suspect that the "carto" compiler isn't going to change any time soon, so I'd presume any "deprecation" isn't going to happen any time soon either.

There's some previous discussion about this [here](https://github.com/gravitystorm/openstreetmap-carto/issues/3183).  [This comment](https://github.com/gravitystorm/openstreetmap-carto/issues/3183#issuecomment-389732544) suggests it's actually an issue in the carto compiler itself.  If using "--quiet" (as also suggested in that thread) (a) works and (b) doesn't suppress any actual errors then by all means submit a pull requests to the scripts that use the "carto" compiler here,

**Comment by simwin** [comment]
Ok, thank you

**Comment by SomeoneElseOSM** [comment]
Closing this; nothing really actionable here.
