### ISSUE TITLE
Render lock gates as ways

### ISSUE THREAD

**Issue by tommycrock** [SomeoneElseOSM/openstreetmap-carto-AJT#5]
Hi Andy, hopefully I've picked the right repository.
I believe [waterway=lock_gate](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dlock_gate) drawn as a way does not render, although it does as a node. I just changed the tagging on [Bingley Five Rise locks](https://map.atownsend.org.uk/maps/map/map.html#18/53.85586/-1.83794) and noticed. It renders on OsmAnd and osm-carto
Cheers
 Tom (TrekClimbing)

**Comment by SomeoneElseOSM** [comment]
Other gates come through as narrow solid lines, so I guess I must have missed that one. I'll have a look.
Narrow solid lines are also used for weirs etc, so there is the  possibility of confusion...

**Comment by SomeoneElseOSM** [comment]
Using the default "linear gate" rendering looks like this:

![Screenshot_20240330_114947](https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/assets/5311740/cf20cfa1-61f4-4e09-9ab5-46b4a896a33b)

that's heavier than I expected, but it is definitely different enough to walls (and weirs) to work.  Here's an example near a dam:

![Screenshot_20240330_115615](https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/assets/5311740/67ec1113-05d9-4066-a939-ee88d72f2090)

I'll go with that - it'll go live at the next release, which will probably be in a week or so.

**Comment by SomeoneElseOSM** [comment]
Resolved by https://github.com/SomeoneElseOSM/SomeoneElse-style/commit/d28f41491630348d95ebe87f0ec814406936e756

**Comment by SomeoneElseOSM** [comment]
Now live at map.atownsend.org.uk
